const employess = [
  { EmployeeCode: '0064', FirstName: 'AAMIR', LastName: 'AZEEM' },
  { EmployeeCode: '0214', FirstName: 'AASIYA', LastName: 'MAID (MATRX LAB)' },
  { EmployeeCode: '0066', FirstName: 'ABDUL', LastName: 'HADI' },
  { EmployeeCode: '0113', FirstName: 'ABDUL', LastName: 'HAFEEZ' },
  { EmployeeCode: '0236', FirstName: 'ABDUL ', LastName: 'HAFEEZ' },
  { EmployeeCode: '0154', FirstName: 'ABDUL', LastName: 'MAJEED' },
  { EmployeeCode: '0030', FirstName: 'ABDUL', LastName: 'RAHEEM' },
  { EmployeeCode: '0133', FirstName: 'ABDUL', LastName: 'RASHEED' },
  { EmployeeCode: '0077', FirstName: 'ABDUL', LastName: 'RAZZAQ' },
  { EmployeeCode: '0183', FirstName: 'ABDUL ', LastName: 'REHMAN ' },
  { EmployeeCode: '0034', FirstName: 'ABDUL', LastName: 'REHMAN' },
  { EmployeeCode: '0053', FirstName: 'ABDUL', LastName: 'REHMAN (LHR)' },
  { EmployeeCode: '0037', FirstName: 'ABDUL', LastName: 'SAMAD' },
  { EmployeeCode: '0215', FirstName: 'ABDUL AZIZ', LastName: 'BALOCH COLONY' },
  { EmployeeCode: '0229', FirstName: 'ABDUL RAHIM', LastName: 'M. AMEEN' },
  { EmployeeCode: '0089', FirstName: 'ABDULLAH', LastName: 'MOOSANI' },
  { EmployeeCode: '0097', FirstName: 'ABDULLAH', LastName: 'SHAMIM' },
  { EmployeeCode: '0198', FirstName: 'ABDULLAH AHMED', LastName: '(STORE)' },
  { EmployeeCode: '0063', FirstName: 'ABUBAKAR', LastName: 'RIAZ' },
  { EmployeeCode: '0201', FirstName: 'ADNAN', LastName: 'SHOKAT' },
  { EmployeeCode: '0029', FirstName: 'AHMED ', LastName: 'DAWOOD' },
  { EmployeeCode: '0058', FirstName: 'AHMED NADEEM', LastName: 'GHAFFAR' },
  {
    EmployeeCode: '0160',
    FirstName: 'ALI',
    LastName: 'GHULAM (MALIR 166, 167)',
  },
  { EmployeeCode: '0151', FirstName: 'ALI', LastName: 'HASSAN (211)' },
  { EmployeeCode: '0224', FirstName: 'ALI AHMED', LastName: 'QURESHI' },
  { EmployeeCode: '0018', FirstName: 'AMAN', LastName: 'RAFIQUE' },
  {
    EmployeeCode: '0234',
    FirstName: 'AMMAR ',
    LastName: 'MITHANI (REJOINING)',
  },
  { EmployeeCode: '0120', FirstName: 'ANAS', LastName: 'KHAN' },
  { EmployeeCode: '0204', FirstName: 'ANEEL', LastName: 'ZULFIQAR MASEEH' },
  { EmployeeCode: '0211', FirstName: 'ANZAL', LastName: 'HYDER' },
  { EmployeeCode: '0205', FirstName: 'AQALZADA', LastName: 'DRIVER' },
  { EmployeeCode: '0092', FirstName: 'ARSALAN', LastName: 'SHEIKH' },
  { EmployeeCode: '0016', FirstName: 'ASAD', LastName: 'ALI' },
  { EmployeeCode: '0010', FirstName: 'ASAD', LastName: 'RAFIQUE' },
  { EmployeeCode: '0175', FirstName: 'ASGHAR', LastName: 'KHAN (JINNAH 28)' },
  { EmployeeCode: '0074', FirstName: 'ASHRAF', LastName: 'IQBAL' },
  { EmployeeCode: '0024', FirstName: 'ASIF ', LastName: 'IBRAHIM' },
  { EmployeeCode: '0008', FirstName: 'ASIM SOHAIL', LastName: 'LIQUAT' },
  { EmployeeCode: '0150', FirstName: 'AYUB', LastName: 'KHAN' },
  { EmployeeCode: '0004', FirstName: 'AZEEM-UL-', LastName: 'HASSAN' },
  { EmployeeCode: '0202', FirstName: 'BAHADUR', LastName: 'KHAN' },
  { EmployeeCode: '0157', FirstName: 'BAKHT', LastName: 'AMIN' },
  { EmployeeCode: '0228', FirstName: 'BAKHT AMIN', LastName: 'KHAN' },
  { EmployeeCode: '0009', FirstName: 'BASHIR', LastName: 'AHMAD' },
  { EmployeeCode: '0096', FirstName: 'BILAL', LastName: 'MARKATIYA' },
  { EmployeeCode: '0222', FirstName: 'BILAL AZIZ', LastName: 'AWAN' },
  {
    EmployeeCode: '0181',
    FirstName: 'DHANI BAKHSH SOOMRO',
    LastName: 'ALLAH WARAYIO SOOMRO',
  },
  { EmployeeCode: '0233', FirstName: 'DR. MUHAMMAD', LastName: 'AAMIR RAZA' },
  { EmployeeCode: '0081', FirstName: 'DR. SARWAR', LastName: 'KHAN' },
  { EmployeeCode: '0080', FirstName: 'DR. SHAHZAD', LastName: 'AHMED' },
  {
    EmployeeCode: '0067',
    FirstName: 'DR. SYED JUNAID',
    LastName: 'AKHTER BUKHARI',
  },
  { EmployeeCode: '0069', FirstName: 'DR. SYED MUHAMMAD', LastName: 'AAMIR' },
  { EmployeeCode: '0119', FirstName: 'EBAD', LastName: 'UL HASSAN' },
  { EmployeeCode: '0126', FirstName: 'FAISAL', LastName: 'ADAM' },
  { EmployeeCode: '0206', FirstName: 'FAIZAN ', LastName: 'ALI (ISB)' },
  { EmployeeCode: '0070', FirstName: 'FAREED', LastName: 'ASHHAB' },
  { EmployeeCode: '0033', FirstName: 'FAREED', LastName: 'KAYANI' },
  { EmployeeCode: '0125', FirstName: 'FARHAN', LastName: 'ALI' },
  {
    EmployeeCode: '0173',
    FirstName: 'FARZANA',
    LastName: 'MASI (EX. MUKHTIARA)',
  },
  { EmployeeCode: '0114', FirstName: 'FARZAND', LastName: 'ALI' },
  {
    EmployeeCode: '0163',
    FirstName: 'G.QADIR',
    LastName: 'ZARDARI (MALIR 158)',
  },
  { EmployeeCode: '0155', FirstName: 'GUL', LastName: 'MOMIN' },
  { EmployeeCode: '0235', FirstName: 'GUL', LastName: 'MUHAMMAD (S.H.WAY)' },
  { EmployeeCode: '0185', FirstName: 'GUL', LastName: 'ZAMAN' },
  { EmployeeCode: '0101', FirstName: 'GUL', LastName: 'ZAMAN' },
  {
    EmployeeCode: '0156',
    FirstName: 'GUL ZAIB',
    LastName: 'J-28 (EX RAFIULLAH)',
  },
  { EmployeeCode: '0177', FirstName: 'GUL ZAMAN', LastName: 'JINNAH 28 ' },
  { EmployeeCode: '0028', FirstName: 'HAFIZ MUHAMMAD ', LastName: 'FAHIM' },
  { EmployeeCode: '0208', FirstName: 'HAFIZ MUHAMMAD', LastName: 'MUSTAFA' },
  { EmployeeCode: '0216', FirstName: 'HALEEMA MAID', LastName: 'MATRX LAB' },
  { EmployeeCode: '0019', FirstName: 'HAMZA', LastName: 'MALIK' },
  { EmployeeCode: '0099', FirstName: 'HASSAN', LastName: 'ABDULLAH' },
  { EmployeeCode: '0168', FirstName: 'HASSAN', LastName: 'KAZMI' },
  { EmployeeCode: '0117', FirstName: 'HASSAN', LastName: 'MUSTAFA' },
  { EmployeeCode: '0171', FirstName: 'ILYAS', LastName: 'SWEEPER' },
  { EmployeeCode: '0039', FirstName: 'IMRAN', LastName: 'A.SATTAR' },
  { EmployeeCode: '0203', FirstName: 'IMTIAZ HUSSAIN ', LastName: 'SOOMRO' },
  { EmployeeCode: '0180', FirstName: 'INAMULLAH', LastName: 'WATCHMAN' },
  { EmployeeCode: '0107', FirstName: 'IQBAL', LastName: 'LODHI' },
  {
    EmployeeCode: '0176',
    FirstName: 'IQBAL',
    LastName: 'WATCHMAN (JINNAH 28)',
  },
  { EmployeeCode: '0199', FirstName: 'IQRA', LastName: 'MAID' },
  { EmployeeCode: '0200', FirstName: 'JAVED', LastName: 'WILLIAM' },
  { EmployeeCode: '0006', FirstName: 'JAWAD', LastName: 'ALI' },
  { EmployeeCode: '0144', FirstName: 'JUMAN', LastName: 'SWEEPER' },
  { EmployeeCode: '0105', FirstName: 'KASHIF', LastName: 'AHSAN' },
  { EmployeeCode: '0225', FirstName: 'KASHIF', LastName: 'IQBAL' },
  { EmployeeCode: '0100', FirstName: 'KASHIF', LastName: 'UDDIN' },
  { EmployeeCode: '0140', FirstName: 'KHADIM', LastName: 'HUSSAIN' },
  { EmployeeCode: '0122', FirstName: 'KHALID', LastName: 'MEHMOOD' },
  { EmployeeCode: '0022', FirstName: 'KHAN SHER', LastName: 'AKBER' },
  { EmployeeCode: '0153', FirstName: 'KHUDA', LastName: 'BUKSH (49)' },
  { EmployeeCode: '0021', FirstName: 'KHURRAM NAWAZ ', LastName: 'GUL' },
  { EmployeeCode: '0115', FirstName: 'KHUWAJA', LastName: 'JUNAID' },
  { EmployeeCode: '0051', FirstName: 'M. ABDUL', LastName: 'NASIR' },
  { EmployeeCode: '0192', FirstName: 'M. AHMED ', LastName: 'NASIM' },
  { EmployeeCode: '0015', FirstName: 'M. ARSHAD', LastName: 'KHURSHEED' },
  { EmployeeCode: '0020', FirstName: 'M. ASAD IQBAL', LastName: 'LODHI' },
  { EmployeeCode: '0073', FirstName: 'M. ASIF', LastName: 'SHAHEEN' },
  { EmployeeCode: '0050', FirstName: 'M.ABBAS', LastName: '(STORE)' },
  { EmployeeCode: '0121', FirstName: 'M.SALMAN', LastName: 'SALEEM' },
  { EmployeeCode: '0017', FirstName: 'M.UMAIR', LastName: 'QAVI' },
  { EmployeeCode: '0054', FirstName: 'MAID', LastName: '(LHR)' },
  { EmployeeCode: '0137', FirstName: 'Malak', LastName: 'Shah' },
  { EmployeeCode: '0104', FirstName: 'MEHMOOD', LastName: 'AWAN' },
  { EmployeeCode: '0090', FirstName: 'MISBAH', LastName: 'CHAGHTAI' },
  { EmployeeCode: '0014', FirstName: 'MISBAHUL ', LastName: 'QAYYUM' },
  { EmployeeCode: '0093', FirstName: 'MOHAMMAD', LastName: 'SOHAIL' },
  { EmployeeCode: '0082', FirstName: 'MOHAMMED OSMAN', LastName: 'KHATRI' },
  { EmployeeCode: '0094', FirstName: 'MOHIDDISAH', LastName: 'AMJAD' },
  {
    EmployeeCode: '0231',
    FirstName: 'MOLA ',
    LastName: 'BAKSH (QUETTA DARBAR)',
  },
  { EmployeeCode: '0170', FirstName: 'MR. SHAFAQAT', LastName: 'ALI' },
  { EmployeeCode: '0085', FirstName: 'MUHAMMAD', LastName: 'AAMIR RAZA' },
  {
    EmployeeCode: '0161',
    FirstName: 'MUHAMMAD',
    LastName: 'AJMAL (MALIR 166, 167)',
  },
  { EmployeeCode: '0138', FirstName: 'MUHAMMAD', LastName: 'AKBAR' },
  { EmployeeCode: '0109', FirstName: 'MUHAMMAD', LastName: 'AMJAD' },
  { EmployeeCode: '0128', FirstName: 'MUHAMMAD', LastName: 'AMMAR' },
  { EmployeeCode: '0084', FirstName: 'MUHAMMAD', LastName: 'ARIF' },
  { EmployeeCode: '0132', FirstName: 'MUHAMMAD', LastName: 'ASIF' },
  { EmployeeCode: '0078', FirstName: 'MUHAMMAD', LastName: 'ATTA' },
  {
    EmployeeCode: '0159',
    FirstName: 'MUHAMMAD',
    LastName: 'AYAZ (MALIR 166, 167)',
  },
  { EmployeeCode: '0055', FirstName: 'MUHAMMAD', LastName: 'AYYAZ' },
  { EmployeeCode: '0103', FirstName: 'MUHAMMAD', LastName: 'BURHAN' },
  {
    EmployeeCode: '0162',
    FirstName: 'MUHAMMAD',
    LastName: 'FAQIRA (MALIR 158)',
  },
  { EmployeeCode: '0072', FirstName: 'MUHAMMAD', LastName: 'FARID' },
  { EmployeeCode: '0047', FirstName: 'MUHAMMAD', LastName: 'FASIH' },
  { EmployeeCode: '0148', FirstName: 'MUHAMMAD', LastName: 'GULISTAN' },
  { EmployeeCode: '0083', FirstName: 'MUHAMMAD', LastName: 'HAROON' },
  { EmployeeCode: '0076', FirstName: 'MUHAMMAD', LastName: 'IMRAN (B-JAIN)' },
  { EmployeeCode: '0049', FirstName: 'MUHAMMAD', LastName: 'IMRAN (STORE)' },
  { EmployeeCode: '0106', FirstName: 'MUHAMMAD', LastName: 'IQBAL' },
  { EmployeeCode: '0131', FirstName: 'MUHAMMAD', LastName: 'ISHTIAQUE' },
  { EmployeeCode: '0158', FirstName: 'MUHAMMAD', LastName: 'JAHANZAIB' },
  { EmployeeCode: '0146', FirstName: 'MUHAMMAD', LastName: 'JAVED' },
  { EmployeeCode: '0112', FirstName: 'MUHAMMAD', LastName: 'KAMRAN' },
  { EmployeeCode: '0041', FirstName: 'MUHAMMAD ', LastName: 'KASHIF' },
  { EmployeeCode: '0145', FirstName: 'MUHAMMAD', LastName: 'MAIRAJ' },
  { EmployeeCode: '0232', FirstName: 'MUHAMMAD', LastName: 'NOMAN (SURG)' },
  { EmployeeCode: '0075', FirstName: 'MUHAMMAD', LastName: 'QASIM' },
  { EmployeeCode: '0011', FirstName: 'MUHAMMAD', LastName: 'RASHID ' },
  { EmployeeCode: '0149', FirstName: 'MUHAMMAD', LastName: 'ROHTAJ' },
  { EmployeeCode: '0217', FirstName: 'MUHAMMAD', LastName: 'SAIM' },
  { EmployeeCode: '0026', FirstName: 'MUHAMMAD', LastName: 'SHAFEEQ' },
  { EmployeeCode: '0071', FirstName: 'MUHAMMAD', LastName: 'SHAHNAWAZ' },
  { EmployeeCode: '0118', FirstName: 'MUHAMMAD', LastName: 'SHARIF' },
  { EmployeeCode: '0143', FirstName: 'MUHAMMAD', LastName: 'SIDDIQUE' },
  { EmployeeCode: '0129', FirstName: 'MUHAMMAD', LastName: 'TALHA' },
  { EmployeeCode: '0226', FirstName: 'MUHAMMAD', LastName: 'UMER JAMAL' },
  { EmployeeCode: '0207', FirstName: 'MUHAMMAD', LastName: 'WAQAR' },
  { EmployeeCode: '0003', FirstName: 'MUHAMMAD', LastName: 'YAHYA' },
  { EmployeeCode: '0102', FirstName: 'MUHAMMAD', LastName: 'YASIR (LAHORE)' },
  { EmployeeCode: '0219', FirstName: 'MUHAMMAD', LastName: 'ZEESHAN JAVID' },
  { EmployeeCode: '0116', FirstName: 'MUHAMMAD', LastName: 'ZUBAIR' },
  { EmployeeCode: '0087', FirstName: 'MUHAMMAD', LastName: 'ZULFIQAR' },
  { EmployeeCode: '0123', FirstName: 'MUHAMMAD ADEEL', LastName: 'IJAZ' },
  { EmployeeCode: '0212', FirstName: 'MUHAMMAD AHMER', LastName: 'FAROOQ' },
  { EmployeeCode: '0193', FirstName: 'MUHAMMAD ARSLAN ', LastName: 'SAIFI' },
  {
    EmployeeCode: '0182',
    FirstName: 'MUHAMMAD FAYYAZ-UD-DIN',
    LastName: 'MUHAMMAD YASEEN',
  },
  { EmployeeCode: '0068', FirstName: 'MUHAMMAD HANIF', LastName: 'GHAZIANI' },
  {
    EmployeeCode: '0167',
    FirstName: 'MUHAMMAD HASHAR',
    LastName: 'ASHRAF (LAHORE)',
  },
  {
    EmployeeCode: '0178',
    FirstName: 'MUHAMMAD NOMAN NAEEM',
    LastName: 'MUHAMMAD NAEEM',
  },
  { EmployeeCode: '0223', FirstName: 'MUHAMMAD UMAR', LastName: 'AYYUB' },
  { EmployeeCode: '0169', FirstName: 'MUHAMMAD UMAR', LastName: 'ZAHEER' },
  { EmployeeCode: '0210', FirstName: 'MUHAMMAD USMAN', LastName: 'BHATTI' },
  { EmployeeCode: '0079', FirstName: 'MUHAMMAD YASIR', LastName: '(AQIB)' },
  { EmployeeCode: '0043', FirstName: 'MUHAMMAD YASIR', LastName: 'MOOSANI' },
  { EmployeeCode: '0142', FirstName: 'MUMTAZ', LastName: 'DRIVER' },
  { EmployeeCode: '0147', FirstName: 'MUNIR', LastName: '(W/M)' },
  { EmployeeCode: '0221', FirstName: 'MUNIR', LastName: '207' },
  { EmployeeCode: '0036', FirstName: 'MUNIR', LastName: 'BADAR' },
  { EmployeeCode: '0165', FirstName: 'MUSTAFA ', LastName: 'SHOAIB' },
  { EmployeeCode: '0086', FirstName: 'MUSTANSAR', LastName: 'JAMIL' },
  { EmployeeCode: '0110', FirstName: 'NADEEM', LastName: 'BAIG' },
  {
    EmployeeCode: '0220',
    FirstName: 'NADIR',
    LastName: 'ABDUL HAFEEZ (MALIR 158)',
  },
  { EmployeeCode: '0174', FirstName: 'NAJEEBULLAH', LastName: 'WATCHMAN' },
  { EmployeeCode: '0141', FirstName: 'NASEEB', LastName: 'KHAN' },
  { EmployeeCode: '0056', FirstName: 'NASIR', LastName: 'KHATIB' },
  { EmployeeCode: '0230', FirstName: 'NIAZ ', LastName: 'ALI (QUETTA DARBAR)' },
  { EmployeeCode: '0045', FirstName: 'NOMAN', LastName: '(RECEPTION)' },
  { EmployeeCode: '0190', FirstName: 'NOUSHEEN', LastName: 'ERUM' },
  { EmployeeCode: '0127', FirstName: 'OSAF AHMED ', LastName: 'KHAN' },
  { EmployeeCode: '0046', FirstName: 'QAMAR', LastName: 'UDDIN' },
  { EmployeeCode: '0152', FirstName: 'QASIM', LastName: 'GABOL (211)' },
  { EmployeeCode: '0136', FirstName: 'RABIA', LastName: 'MASI' },
  { EmployeeCode: '0164', FirstName: 'RAHIB', LastName: 'MUSHTAQ' },
  {
    EmployeeCode: '0187',
    FirstName: 'RAHIM DINO',
    LastName: 'S.H.WAY FACTORY',
  },
  { EmployeeCode: '0002', FirstName: 'RASHID ', LastName: 'HUSSAIN' },
  { EmployeeCode: '0095', FirstName: 'RASHID', LastName: 'KHAN' },
  { EmployeeCode: '0013', FirstName: 'RASHID', LastName: 'NAWAB' },
  { EmployeeCode: '0031', FirstName: 'REHAN', LastName: 'SAEED' },
  { EmployeeCode: '0188', FirstName: 'SABIHA ', LastName: 'MUNIR' },
  { EmployeeCode: '0027', FirstName: 'SADIQ', LastName: 'DAWOOD' },
  { EmployeeCode: '0098', FirstName: 'SALMAN', LastName: 'FAREED' },
  { EmployeeCode: '0062', FirstName: 'SANA', LastName: 'ULLAH' },
  { EmployeeCode: '0005', FirstName: 'SHABAN', LastName: 'ALI' },
  { EmployeeCode: '0088', FirstName: 'SHAHAN', LastName: 'ALI' },
  { EmployeeCode: '0209', FirstName: 'SHAHID', LastName: 'WATCHMEN' },
  { EmployeeCode: '0007', FirstName: 'SHAHZAD HUSSAIN', LastName: 'CHAUDHRY' },
  { EmployeeCode: '0166', FirstName: 'SHAHZAIB', LastName: 'SOHAIL (LAHORE)' },
  { EmployeeCode: '0135', FirstName: 'SHAKEEL', LastName: '(GARDENING)' },
  { EmployeeCode: '0091', FirstName: 'SHAKIL', LastName: 'GHAZIANI' },
  { EmployeeCode: '0184', FirstName: 'SHANI', LastName: 'KHAN' },
  { EmployeeCode: '0139', FirstName: 'SHER', LastName: 'ALI' },
  { EmployeeCode: '0197', FirstName: 'SHER NAWAZ', LastName: 'KHAN' },
  { EmployeeCode: '0040', FirstName: 'SHOAIB', LastName: 'YOUNUS' },
  { EmployeeCode: '0172', FirstName: 'SHUMAILA', LastName: 'MASI' },
  { EmployeeCode: '0227', FirstName: 'SIDDIQUE', LastName: 'UR REHMAN' },
  { EmployeeCode: '0196', FirstName: 'SM ZAIN-UL-', LastName: 'ABIDEEN' },
  { EmployeeCode: '0218', FirstName: 'SYED ABBAS', LastName: 'RAZA NAQVI' },
  { EmployeeCode: '0023', FirstName: 'SYED ABID', LastName: 'HUSSAIN' },
  { EmployeeCode: '0061', FirstName: 'SYED ABRAR', LastName: 'HUSSAIN' },
  { EmployeeCode: '0025', FirstName: 'SYED MOHSIN', LastName: 'ALI' },
  { EmployeeCode: '0060', FirstName: 'SYED MUHAMMAD', LastName: 'UMAIR NASIM' },
  {
    EmployeeCode: '0108',
    FirstName: 'SYED NAVEED',
    LastName: 'AHMED TABASSUM',
  },
  { EmployeeCode: '0111', FirstName: 'SYED SALMAN', LastName: 'ALI' },
  { EmployeeCode: '0052', FirstName: 'TAHIR', LastName: 'YOUNUS' },
  { EmployeeCode: '0032', FirstName: 'TEHSEEN', LastName: 'AFZAL' },
  { EmployeeCode: '0213', FirstName: 'TOHEED', LastName: 'AZMAT' },
  { EmployeeCode: '0195', FirstName: 'TOUSEEF ', LastName: 'QASIM' },
  { EmployeeCode: '0042', FirstName: 'UMAIR', LastName: 'SADIQ' },
  { EmployeeCode: '0048', FirstName: 'UMER', LastName: 'TAJ' },
  { EmployeeCode: '0012', FirstName: 'UMER ALI', LastName: 'GILL' },
  { EmployeeCode: '0130', FirstName: 'USMAN', LastName: 'ALI' },
  { EmployeeCode: '0001', FirstName: 'USMAN ', LastName: 'GHANI' },
  { EmployeeCode: '0191', FirstName: 'WAQAS', LastName: 'MAHMOOD' },
  { EmployeeCode: '0189', FirstName: 'WARISHA', LastName: 'NADEEM' },
  { EmployeeCode: '0044', FirstName: 'WASEEM', LastName: 'SUPPLIER' },
  { EmployeeCode: '0038', FirstName: 'WASEEM', LastName: 'WAHEED' },
  { EmployeeCode: '0065', FirstName: 'WASTABIR', LastName: 'RAAD' },
  { EmployeeCode: '0124', FirstName: 'YAHYA', LastName: 'SHAMSI' },
  { EmployeeCode: '0057', FirstName: 'ZAHEER', LastName: 'ALAM' },
  { EmployeeCode: '0134', FirstName: 'ZAHIR', LastName: 'SHAH' },
  { EmployeeCode: '0194', FirstName: 'ZAKIR ULLAH', LastName: 'HAMID KHAN' },
  { EmployeeCode: '0059', FirstName: 'ZIA UR', LastName: 'REHMAN' },
  { EmployeeCode: '0035', FirstName: 'ZULFIQAR', LastName: 'ALI' },
];

const customers = [
  {
    id: '3958dc9e-712f-4377-85e9-fec4b6a6442a',
    name: 'Delba de Oliveira',
    email: 'delba@oliveira.com',
    image_url: '/customers/delba-de-oliveira.png',
  },
  {
    id: '3958dc9e-742f-4377-85e9-fec4b6a6442a',
    name: 'Lee Robinson',
    email: 'lee@robinson.com',
    image_url: '/customers/lee-robinson.png',
  },
  {
    id: '3958dc9e-737f-4377-85e9-fec4b6a6442a',
    name: 'Hector Simpson',
    email: 'hector@simpson.com',
    image_url: '/customers/hector-simpson.png',
  },
  {
    id: '50ca3e18-62cd-11ee-8c99-0242ac120002',
    name: 'Steven Tey',
    email: 'steven@tey.com',
    image_url: '/customers/steven-tey.png',
  },
  {
    id: '3958dc9e-787f-4377-85e9-fec4b6a6442a',
    name: 'Steph Dietz',
    email: 'steph@dietz.com',
    image_url: '/customers/steph-dietz.png',
  },
  {
    id: '76d65c26-f784-44a2-ac19-586678f7c2f2',
    name: 'Michael Novotny',
    email: 'michael@novotny.com',
    image_url: '/customers/michael-novotny.png',
  },
  {
    id: 'd6e15727-9fe1-4961-8c5b-ea44a9bd81aa',
    name: 'Evil Rabbit',
    email: 'evil@rabbit.com',
    image_url: '/customers/evil-rabbit.png',
  },
  {
    id: '126eed9c-c90c-4ef6-a4a8-fcf7408d3c66',
    name: 'Emil Kowalski',
    email: 'emil@kowalski.com',
    image_url: '/customers/emil-kowalski.png',
  },
  {
    id: 'CC27C14A-0ACF-4F4A-A6C9-D45682C144B9',
    name: 'Amy Burns',
    email: 'amy@burns.com',
    image_url: '/customers/amy-burns.png',
  },
  {
    id: '13D07535-C59E-4157-A011-F8D2EF4E0CBB',
    name: 'Balazs Orban',
    email: 'balazs@orban.com',
    image_url: '/customers/balazs-orban.png',
  },
];
